export const projectData = [
    {
        title: "Stan Lee Tribute",
        image: "https://www.youtube.com/embed/jbZuNXhKoWw",
        description: "My first project ever! This is a responsive webpage written in HTML and CSS with a mobile-first design.",
        netlify: "https://stan-lee-tribute-page.netlify.com/",
        github: "https://github.com/marthasharpe/Stan-Lee-Tribute-Page",
        date: 4.1,
        technology: [],
    },
    {
        title: "Bartending Game",
        image: "https://www.youtube.com/embed/zLNYzg27QPk",
        description: "A game to learn how to mix different drinks. I designed and wrote this from scratch using Vanilla Javascript.",
        netlify: "https://bartending-game.netlify.com/",
        github: "https://github.com/marthasharpe/Bartending-Game",
        date: 5.1,
        technology: ["JavaScript"],
    },
    {
        title: "React Calculator",
        image: "https://www.youtube.com/embed/zdhsM7_njvM",
        description: "I built a simple immediate-execution calculator using React and CSS Grid. Calculators require a lot of logic!",
        netlify: "https://simple-react-calculator.netlify.com",
        github: "https://github.com/marthasharpe/react-calculator",
        date: 6.1,
        technology: ["React"],
    },
    {
        title: "React Pomodoro Clock",
        image: "https://www.youtube.com/embed/kEk-CObPIIk",
        description: "Learned to use React Hooks for this project. I also got to ask a question on StackOverflow for the first time!",
        netlify: "https://react-pomodoro-clock.netlify.com",
        github: "https://github.com/marthasharpe/react-pomodoro-clock",
        date: 7.1,
        technology: ["React"],
    },
    {
        title: "Redux Pomodoro Clock",
        image: "https://www.youtube.com/embed/wu2hvrGfRnE",
        description: "Used React-Redux to build the same Pomodoro Clock. Setting up Redux was challenging but very rewarding.",
        netlify: "https://react-pomodoro-clock.netlify.com",
        github: "https://github.com/marthasharpe/redux-practice-app",
        date: 7.2,
        technology: ["React", "Redux"],
    },
    {
        title: "Random Joke App",
        image: "https://www.youtube.com/embed/pTvgmmzq67s",
        description: "Figured out how to fetch data from a third-party API for this project. Also deployed to Netlify for all to enjoy!",
        netlify: "https://getjokes.netlify.com",
        github: "https://github.com/marthasharpe/random-quote-machine",
        date: 8.1,
        technology: ["React"],
    },
    {
        title: "Pig Latin Translator",
        image: "https://www.youtube.com/embed/Y2_1YDRGlVI",
        description: "Learned how RESTful APIs are made and how to handle errors. Also put my regular expression skills to good use!",
        netlify: "https://pig-latin-translator.netlify.com/",
        github: "https://github.com/marthasharpe/Pig-Latin-Wisdom",
        date: 9.1,
        technology: ["React"],
    },
    {
        title: "Hangémon",
        image: "https://www.youtube.com/embed/s3mlI2ZdhTs",
        description: "I created a hangman game using the Pokémon API. Getting the hang of using Redux to manage state.",
        netlify: "https://hangemon.netlify.com/",
        github: "https://github.com/marthasharpe/hang-pokemon",
        date: 10.1,
        technology: ["React", "Redux"],
    },
]