export const featuredProjects = [
    // {
    //     title: "MySchool: Full-Stack Web App",
    //     image: "https://www.youtube-nocookie.com/embed/eR6Su2uIC8o",
    //     description: "A website for saving online learning resources. Built a REST API using Node, Express, and MongoDB with Mongoose schemas. Implemented user login with password encryption and JWT authentication. Client-side is a basic CRUD application built with React. Used Redux for state management and redux-thunk for asynchronous API calls. Also used React-Router-DOM for dynamic routing and React-Bootstrap for styling.",
    //     date: "March 2020",
    //     netlify: "https://my-school.netlify.com/",
    //     github: "https://github.com/marthasharpe/MySchool-front",
    // },
    {
        title: "Hangémon: React-Redux Game",
        image: "https://www.youtube-nocookie.com/embed/IaLdSdVeCec",
        description: "Created a hangman game fetching data from the open-source Pokémon API. Used Redux-Thunk for the asynchronous API call. Mobile-first design using React-Bootstrap. Learned to control all aspects of the UI using Redux state.",
        date: "November 2019",
        netlify: "https://hangemon.netlify.com/",
        github: "https://github.com/marthasharpe/hang-pokemon",
    },
    {
        title: "MixMaster: JavaScript Game",
        image: "https://www.youtube-nocookie.com/embed/zLNYzg27QPk",
        description: "A game to learn to mix cocktails. Original concept and design from my bartending days. I wrote this from scratch using ES6 JavaScript and styled it with CSS grid and flexbox. Used an object-oriented approach by creating a Drink class constructor.",
        date: "August 2019",
        netlify: "https://bartending-game.netlify.com/",
        github: "https://github.com/marthasharpe/Bartending-Game",
    },
]

export const projectData = [
    {
        title: "Stan Lee Tribute",
        image: "https://www.youtube-nocookie.com/embed/jbZuNXhKoWw",
        description: "My first project ever! This is a responsive webpage written in HTML and CSS with a mobile-first design.",
        netlify: "https://stan-lee-tribute-page.netlify.com/",
        github: "https://github.com/marthasharpe/Stan-Lee-Tribute-Page",
        date: 4.1,
        technology: [],
    },
    {
        title: "Bartending Game",
        image: "https://www.youtube-nocookie.com/embed/zLNYzg27QPk",
        description: "A game to learn how to mix different drinks. Designed and wrote this from scratch using Vanilla Javascript.",
        netlify: "https://bartending-game.netlify.com/",
        github: "https://github.com/marthasharpe/Bartending-Game",
        date: 5.1,
        technology: ["JavaScript"],
    },
    {
        title: "React Calculator",
        image: "https://www.youtube-nocookie.com/embed/zdhsM7_njvM",
        description: "Built a simple immediate-execution calculator using React and CSS Grid. Calculators require a lot of logic!",
        netlify: "https://simple-react-calculator.netlify.com",
        github: "https://github.com/marthasharpe/react-calculator",
        date: 6.1,
        technology: ["React"],
    },
    {
        title: "React Drum Kit",
        image: "https://www.youtube-nocookie.com/embed/PjTAL3Ja3a0",
        description: "Tackled lifecycle methods in React for this project, working with event listeners, refs, and transitions.",
        netlify: "https://react-drumset.netlify.com/",
        github: "https://github.com/marthasharpe/React-Drum-Set",
        date: 6.2,
        technology: ["React"],
    },
    {
        title: "React Pomodoro Clock",
        image: "https://www.youtube-nocookie.com/embed/kEk-CObPIIk",
        description: "Learned to use React Hooks for this project. Also got to ask a question on StackOverflow for the first time!",
        netlify: "https://react-pomodoro-clock.netlify.com",
        github: "https://github.com/marthasharpe/react-pomodoro-clock",
        date: 7.1,
        technology: ["React"],
    },
    {
        title: "Redux Pomodoro Clock",
        image: "https://www.youtube-nocookie.com/embed/wu2hvrGfRnE",
        description: "Used React-Redux to build the same Pomodoro Clock. Setting up Redux was challenging but very rewarding.",
        netlify: "https://react-pomodoro-clock.netlify.com",
        github: "https://github.com/marthasharpe/redux-practice-app",
        date: 7.2,
        technology: ["React", "Redux"],
    },
    {
        title: "Random Joke App",
        image: "https://www.youtube-nocookie.com/embed/pTvgmmzq67s",
        description: "Figured out how to fetch data from a third-party API for this project. Also deployed to Netlify for all to enjoy!",
        netlify: "https://getjokes.netlify.com",
        github: "https://github.com/marthasharpe/random-quote-machine",
        date: 8.1,
        technology: ["React"],
    },
    {
        title: "Pig Latin Translator",
        image: "https://www.youtube-nocookie.com/embed/XXYCSKrTYt4",
        description: "Put my regular expressions skills to good use and got some great practice using algorithms to handle edge cases.",
        netlify: "https://pig-latin-translator.netlify.com/",
        github: "https://github.com/marthasharpe/Pig-Latin-Wisdom",
        date: 9.1,
        technology: ["React"],
    },
    {
        title: "Hangémon",
        image: "https://www.youtube-nocookie.com/embed/IaLdSdVeCec",
        description: "Created a hangman game using the Pokémon API. Used Redux to manage state and React-Bootstrap for styling.",
        netlify: "https://hangemon.netlify.com/",
        github: "https://github.com/marthasharpe/hang-pokemon",
        date: 10.1,
        technology: ["React", "Redux", "Bootstrap"],
        featured: true
    },
    {
        title: "Sorted Card Carousel",
        image: "https://www.youtube-nocookie.com/embed/XGkD5Mvf9oM",
        description: "This was a coding challenge to display data from a JSON file on cards in a single row. Also wrote my first unit test.",
        netlify: "https://sorted-card-carousel.netlify.com/",
        github: "https://github.com/marthasharpe/card-carousel-app",
        date: 11.1,
        technology: ["React", "Redux", "Bootstrap"],
    },
    {
        title: "Portfolio Page",
        image: "https://www.youtube-nocookie.com/embed/PbVEyLqZmI8",
        description: "Remade my portfolio page using react-bootstrap. Projects can be sorted by date or filtered by technology.",
        netlify: "https://marthasharpe.netlify.com/",
        github: "https://github.com/marthasharpe/Martha-Sharpe-Codes",
        date: 11.2,
        technology: ["React", "Bootstrap"],
    },
    {
        title: "The Form of Death",
        image: "https://www.youtube-nocookie.com/embed/ZWJQVfQ9oeA",
        description: "This project gave me some practice working with step-forms in React. Also learned some Material-UI for the styling.",
        netlify: "https://form-of-death.netlify.com/",
        github: "https://github.com/marthasharpe/react-form",
        date: 12.1,
        technology: ["React", "Bootstrap"],
    },
]